#spring.application.name=server
#server.port=9001
#eureka.client.serviceUrl.defaultZone=http://localhost:3333/eureka/
server:
  port: 9001
spring:
  application:
    name: server
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: admin
        password: admin
#spring.boot.admin.client.url=http://localhost:8888
#spring.boot.admin.client.username=admin
#spring.boot.admin.client.password=admin
#management.endpoints.web.exposure.include="*"
#management.endpoint.health.show-details=always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3333/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file: /work/logs/debug.log